name: Build, Test, and Deploy AWS Lambda

on:
  push:
    branches:
      - dev
    tags:
      - v1.*

jobs:


  # the first thing is for us to build the repo
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up node.js 
        uses: actions/setup-node@v6
        with:
          node-version: '24.12.0'
      - run: npm install #this installs npm
      - run: npm build

#       - name: Install dependencies & package Lambda
#         run: |
#           python -m pip install --upgrade pip
#           mkdir package
#           pip install -r requirements.txt -t package
#           cp *.py package/
#           cd package
#           zip -r ../function.zip .

#       - name: Upload build artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: lambda-package
#           path: function.zip


  
#   # the second step after build is to test the using the python pytest
#   test:
#     needs: build
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'

#       - name: Install dependencies for testing
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#           pip install pytest coverage

#       - name: Run tests
#         run: |
#           coverage run -m pytest -v -s

#       - name: Coverage report
#         run: |
#           coverage report -m
# #now are deploying the lambda function to aws meaning testing succeeded as unit test
#   deploy: 
#     needs: test
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Download build artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: lambda-package
#           path: .

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: eu-north-1

#       - name: Deploy Lambda Function
#         run: |
#           aws lambda update-function-code \
#             --function-name customers \
#             --zip-file fileb://function.zip

